// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: comments.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getTotalComments = `-- name: GetTotalComments :one
SELECT COUNT(*) FROM comments WHERE poll_id = $1
`

func (q *Queries) GetTotalComments(ctx context.Context, pollID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalComments, pollID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
