// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: restrictedWords.sql

package database

import (
	"context"
)

const addRestrictedWord = `-- name: AddRestrictedWord :one
Insert into restrictedWords (word) values ($1) returning id, word, created_at, updated_at
`

func (q *Queries) AddRestrictedWord(ctx context.Context, word string) (Restrictedword, error) {
	row := q.db.QueryRowContext(ctx, addRestrictedWord, word)
	var i Restrictedword
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllRestrictedWords = `-- name: GetAllRestrictedWords :one
Select ARRAY_AGG(word) from restrictedWords
`

func (q *Queries) GetAllRestrictedWords(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getAllRestrictedWords)
	var array_agg interface{}
	err := row.Scan(&array_agg)
	return array_agg, err
}
