// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restrictedWords.sql

package database

import (
	"context"

	"github.com/lib/pq"
)

const addRestrictedWord = `-- name: AddRestrictedWord :one
INSERT INTO restrictedWords (word) 
VALUES ($1) 
ON CONFLICT (word) DO NOTHING
RETURNING id, word, created_at, updated_at
`

func (q *Queries) AddRestrictedWord(ctx context.Context, word string) (Restrictedword, error) {
	row := q.db.QueryRowContext(ctx, addRestrictedWord, word)
	var i Restrictedword
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addRestrictedWordsBatch = `-- name: AddRestrictedWordsBatch :exec
INSERT INTO restrictedWords (word)
SELECT unnest($1::text[])
ON CONFLICT (word) DO NOTHING
`

func (q *Queries) AddRestrictedWordsBatch(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.ExecContext(ctx, addRestrictedWordsBatch, pq.Array(dollar_1))
	return err
}

const getAllRestrictedWords = `-- name: GetAllRestrictedWords :many
SELECT word FROM restrictedWords
`

func (q *Queries) GetAllRestrictedWords(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllRestrictedWords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var word string
		if err := rows.Scan(&word); err != nil {
			return nil, err
		}
		items = append(items, word)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
