// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const checkUserNameExists = `-- name: CheckUserNameExists :one
SELECT EXISTS(
    Select 1
FROM
    users
WHERE
    user_name = $1
    ) as exists
`

func (q *Queries) CheckUserNameExists(ctx context.Context, userName sql.NullString) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserNameExists, userName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (email, first_name, last_name, hashed_password,provider,provider_id,role,picture_url)
VALUES

    ($1, $2, $3, $4, $5,$6,$7,$8)
RETURNING
    id, created_at, updated_at, user_name, email, first_name, last_name, hashed_password, provider, provider_id, role, picture_url
`

type CreateUserParams struct {
	Email          string
	FirstName      string
	LastName       sql.NullString
	HashedPassword sql.NullString
	Provider       sql.NullString
	ProviderID     sql.NullString
	Role           string
	PictureUrl     sql.NullString
}

// used by auth handler
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.HashedPassword,
		arg.Provider,
		arg.ProviderID,
		arg.Role,
		arg.PictureUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.HashedPassword,
		&i.Provider,
		&i.ProviderID,
		&i.Role,
		&i.PictureUrl,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM
    users
WHERE
    id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id, created_at, updated_at, user_name, email, first_name, last_name, hashed_password, provider, provider_id, role, picture_url
FROM
    users
WHERE
    email = $1
`

// used by auth handler
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.HashedPassword,
		&i.Provider,
		&i.ProviderID,
		&i.Role,
		&i.PictureUrl,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT
    id, created_at, updated_at, user_name, email, first_name, last_name, hashed_password, provider, provider_id, role, picture_url
FROM
    users
WHERE
    id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.HashedPassword,
		&i.Provider,
		&i.ProviderID,
		&i.Role,
		&i.PictureUrl,
	)
	return i, err
}

const getUserByProviderAndProviderId = `-- name: GetUserByProviderAndProviderId :one
SELECT
    id, created_at, updated_at, user_name, email, first_name, last_name, hashed_password, provider, provider_id, role, picture_url
FROM
    users
WHERE
    provider = $1 AND provider_id = $2
`

type GetUserByProviderAndProviderIdParams struct {
	Provider   sql.NullString
	ProviderID sql.NullString
}

// used by auth handler
func (q *Queries) GetUserByProviderAndProviderId(ctx context.Context, arg GetUserByProviderAndProviderIdParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByProviderAndProviderId, arg.Provider, arg.ProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.HashedPassword,
		&i.Provider,
		&i.ProviderID,
		&i.Role,
		&i.PictureUrl,
	)
	return i, err
}

const getUserStats = `-- name: GetUserStats :one
SELECT
    (SELECT COUNT(*) FROM polls WHERE polls.user_id = $1) as total_polls,
    (SELECT COUNT(*) FROM comments WHERE comments.poll_id IN (SELECT id FROM polls WHERE polls.user_id = $1)) as total_comments,
    (SELECT COUNT(*) FROM votes WHERE votes.poll_id IN (SELECT id FROM polls WHERE polls.user_id = $1)) as total_votes
FROM users
WHERE users.id = $1
`

type GetUserStatsRow struct {
	TotalPolls    int64
	TotalComments int64
	TotalVotes    int64
}

func (q *Queries) GetUserStats(ctx context.Context, userID uuid.UUID) (GetUserStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserStats, userID)
	var i GetUserStatsRow
	err := row.Scan(&i.TotalPolls, &i.TotalComments, &i.TotalVotes)
	return i, err
}

const getUsers = `-- name: GetUsers :many
Select
    id, created_at, updated_at, user_name, email, first_name, last_name, hashed_password, provider, provider_id, role, picture_url
FROM
    users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.HashedPassword,
			&i.Provider,
			&i.ProviderID,
			&i.Role,
			&i.PictureUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserAvatar = `-- name: UpdateUserAvatar :one
UPDATE users
SET picture_url = $2,
    updated_at = NOW()
where id = $1
RETURNING id, created_at, updated_at, user_name, email, first_name, last_name, hashed_password, provider, provider_id, role, picture_url
`

type UpdateUserAvatarParams struct {
	ID         uuid.UUID
	PictureUrl sql.NullString
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserAvatar, arg.ID, arg.PictureUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.HashedPassword,
		&i.Provider,
		&i.ProviderID,
		&i.Role,
		&i.PictureUrl,
	)
	return i, err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE
    users
SET
    user_name =  $1,
    updated_at = NOW()
WHERE id = $2 RETURNING id, created_at, updated_at, user_name, email, first_name, last_name, hashed_password, provider, provider_id, role, picture_url
`

type UpdateUserNameParams struct {
	UserName sql.NullString
	ID       uuid.UUID
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserName, arg.UserName, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.HashedPassword,
		&i.Provider,
		&i.ProviderID,
		&i.Role,
		&i.PictureUrl,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE
    users
SET
    email = COALESCE($1, email),
    first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    user_name = COALESCE($4, user_name),
    updated_at = NOW()
WHERE id = $5 RETURNING id, created_at, updated_at, user_name, email, first_name, last_name, hashed_password, provider, provider_id, role, picture_url
`

type UpdateUserProfileParams struct {
	Email     string
	FirstName string
	LastName  sql.NullString
	UserName  sql.NullString
	ID        uuid.UUID
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.UserName,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.HashedPassword,
		&i.Provider,
		&i.ProviderID,
		&i.Role,
		&i.PictureUrl,
	)
	return i, err
}
