services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env 
    volumes:
      - ./localhost+2.pem:/app/certs/cert.pem:ro
      - ./localhost+2-key.pem:/app/certs/key.pem:ro
    environment:
      # Add your database connection environment variables here
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=ghostvox
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=postgres://postgres:${DB_PASSWORD}@db:5432/ghostvox?sslmode=disable
      - TLS_CERT_PATH=/app/certs/cert.pem
      - TLS_KEY_PATH=/app/certs/key.pem
   

  db:
    image: postgres:15 # Specify version for reproducibility
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ghostvox
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:


