name: Develop workflow
on:
  push:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build binary
        run: go build -o ghostvox-backend .

      - name: Run tests
        # This step automatically runs after the "Build binary" step succeeds.
        run: go test -v ./...
